name: Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AWS_SECRET_ACCESS_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Debug: Check connection and directory
          echo "Connected to EC2"
          ls -la /gamehorizon || echo "Directory does not exist"

          cd /gamehorizon || exit

          # Debug: Check Git and Node.js setup
          git --version || echo "Git is not installed"
          node --version || echo "Node.js is not installed"

          # Pull the latest code
          git pull origin master


          # Install dependencies
          npm install --production

          # Debug: Check PM2 setup
          pm2 --version || echo "PM2 is not installed"

          # Restart the application using pm2
          pm2 reload all --update-env || pm2 start index.js --name gamehorizon
        EOF
